---
- name: ensure local_xxx filter files are installed (Debian8)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: logcheck
    mode: 0644
  with_items:
    - { src: 'Debian8/local_ansible', dest: '/etc/logcheck/ignore.d.server/local_ansible' }
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"


