---
# tasks file for logcheck

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "defaults/{{ ansible_distribution }}.yml"
    - "defaults/defaults.yml"
  tags: vars


- name: ensure logcheck is installed (yum)
  yum: name=logcheck state=present
  when: ansible_pkg_mgr == "yum"

- name: ensure logcheck is installed (apt)
  apt: name=logcheck state=present
  when: ansible_pkg_mgr == "apt"

- name: ensure logcheck is installed (openbsd_pkg)
  openbsd_pkg: name=logcheck state=present
  when: ansible_pkg_mgr == "openbsd_pkg"

- name: ensure logcheck user is in group for logfile access
  user:
    name: "{{ logcheck_user }}"
    groups: "{{ logcheck_group_for_logfile_access }}"
    append: yes
    createhome: no

- name: update logcheck.conf
  template:
    src: templates/logcheck.conf.j2
    dest: /etc/logcheck/logcheck.conf
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0640

- name: update logcheck.logfiles
  template:
    src: templates/logcheck.logfiles.j2
    dest: /etc/logcheck/logcheck.logfiles
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0640

- name: install local_xxx pattern files in ignore.d.* directory (OpenBSD)
  copy:
    src: "{{ item }}"
    dest: "/etc/logcheck/ignore.d.server/{{ item | basename }}"
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0644
  with_fileglob: "OpenBSD/local*"
  when: ansible_distribution == "OpenBSD"

- name: install local_xxx pattern files in ignore.d.* directory
  copy:
    src: "{{ item }}"
    dest: "/etc/logcheck/ignore.d.server/{{ item | basename }}"
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0644
  with_fileglob: "{{ logcheck_distribution_directory }}/local*"

- name: install local_xxx pattern files in violations.d directory
  copy:
    src: "{{ item }}"
    dest: "/etc/logcheck/violations.d/{{ item | basename | regex_replace('^violations_', '') }}"
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0644
  with_fileglob: "{{ logcheck_distribution_directory }}/violations_local*"

- name: ensure logcheck cron job is installed (OpenBSD)
  cron:
    name: "logcheck"
    minute: "2"
    job: "if [ -x /usr/local/bin/logcheck ]; then doas -u {{ logcheck_user }} nice -n10 /usr/local/bin/logcheck; fi"
  when: ansible_distribution == "OpenBSD"

