---
- name: ensure logcheck is installed (Debian)
  apt: name=logcheck state=present
  when: ansible_distribution == "Debian"

- name: ensure logcheck is installed (OpenBSD)
  openbsd_pkg: name=logcheck state=present
  when: ansible_distribution == "OpenBSD"

- name: update logcheck.conf
  template:
    src: template/logcheck.conf.j2
    dest: /etc/logcheck/logcheck.conf
    owner: root
    group: "{{ logcheck_group }}"
    mode: 0640

- name: update logcheck.logfiles
  template:
    src: template/logcheck.logfiles.j2
    dest: /etc/logcheck/logcheck.logfiles
    owner: root
    group: "{{ logcheck_group }}"
    mode: 0640

- include: debian8.yml
  static: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- include: debian9.yml
  static: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"

- include: openbsd.yml
  static: yes
  when: ansible_distribution == "OpenBSD"

