---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "defaults/{{ ansible_distribution }}.yml"
    - "defaults/defaults.yml"
  tags: vars


- name: ensure logcheck is installed (Debian)
  apt: name=logcheck state=present
  when: ansible_distribution == "Debian"

- name: ensure logcheck is installed (OpenBSD)
  openbsd_pkg: name=logcheck state=present
  when: ansible_distribution == "OpenBSD"

- name: ensure logcheck user is in group for logfile access
  user:
    name: "{{ logcheck_user }}"
    groups: "{{ logcheck_group_for_logfile_access }}"
    append: yes
    createhome: no

- name: update logcheck.conf
  template:
    src: template/logcheck.conf.j2
    dest: /etc/logcheck/logcheck.conf
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0640

- name: update logcheck.logfiles
  template:
    src: template/logcheck.logfiles.j2
    dest: /etc/logcheck/logcheck.logfiles
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0640

- name: ensure common local_xxx filter files are installed (Debian 8)
  copy:
    src: "{{ logcheck_distribution_directory }}/{{ item }}"
    dest: "/etc/logcheck/ignore.d.server/{{ item }}"
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0644
  with_items: "{{ logcheck_filter_files }}"
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- include: debian9.yml
  static: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"

- name: ensure common local_xxx filter files are installed (OpenBSD)
  copy:
    src: "{{ logcheck_distribution_directory }}/{{ item }}"
    dest: "/etc/logcheck/ignore.d.server/{{ item }}"
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0644
  with_items: "{{ logcheck_filter_files }}"
  when: ansible_distribution == "OpenBSD"

- include: openbsd.yml
  static: yes
  when: ansible_distribution == "OpenBSD"

