---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "defaults/{{ ansible_distribution }}.yml"
    - "defaults/defaults.yml"
  tags: vars


- name: ensure logcheck is installed (Debian)
  apt: name=logcheck state=present
  when: ansible_distribution == "Debian"

- name: ensure logcheck is installed (OpenBSD)
  openbsd_pkg: name=logcheck state=present
  when: ansible_distribution == "OpenBSD"

- name: ensure logcheck user is in group for logfile access
  user:
    name: "{{ logcheck_user }}"
    groups: "{{ logcheck_group_for_logfile_access }}"
    append: yes
    createhome: no

- name: update logcheck.conf
  template:
    src: template/logcheck.conf.j2
    dest: /etc/logcheck/logcheck.conf
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0640

- name: update logcheck.logfiles
  template:
    src: template/logcheck.logfiles.j2
    dest: /etc/logcheck/logcheck.logfiles
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0640

- name: ensure local_xxx pattern files are installed in ignore.d.* directory
  copy:
    src: "{{ item }}"
    dest: "/etc/logcheck/ignore.d.server/{{ item | basename }}"
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0644
  with_fileglob: "{{ logcheck_distribution_directory }}/local*"

- name: ensure local_xxx pattern files are installed in violations.d directory
  copy:
    src: "{{ item }}"
    dest: "/etc/logcheck/violations.d/{{ item | basename | regex_replace('^violations_', '') }}"
    owner: root
    group: "{{ logcheck_group_for_config }}"
    mode: 0644
  with_fileglob: "{{ logcheck_distribution_directory }}/violations_local*"

